# Generated by Django 3.2.23 on 2023-12-23 05:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='display_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('DEPARTMENT', 'department'), ('CONTACTS', 'contacts'), ('POSITIONS', 'positions'), ('LOCATION', 'location')], max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
